### ISSUE TITLE
Add healthcheck endpoint aggregating healthcheck for all remote applications

### ISSUE THREAD

**Issue by claustres** [kalisio/feathers-distributed#109]
Now we can only check by application key but we should expose a global healthcheck endpoint aggregating all results.

**Comment by nathanbrizzee-cdcr** [comment]
Hi @claustres 
For some reason this isn't running today. It worked yesterday (at least I thought it did).  Today, with no changes, I get the following error when I use a gateway and one other server.  The gateway runs but the other server crashes on the registration of the services from the gateway step with the following error:

package.json
```json
    "@kalisio/feathers-distributed": "kalisio/feathers-distributed#636a6f42c3d830652e1a93a8f9939809cec9cfce",
```
Console output
```
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/`
warn: Publishing all events to all authenticated users. See `channels.js` and https://docs.feathersjs.com/api/channels.html for more information.
  feathers-distributed Initializing feathers-distributed with options {
  publicationDelay: 10000,
  componentDelay: 1000,
  coteDelay: undefined,
  heartbeatInterval: undefined,
  middlewares: { before: [Function: before] },
  publishEvents: true,
  distributedEvents: [ 'created', 'updated', 'patched', 'removed' ],
  distributedMethods: [ 'find', 'get', 'create', 'update', 'patch', 'remove' ],
  hooks: { before: { all: [Array] } },
  services: [Function: services],
  remoteServices: [Function: remoteServices],
  key: 'ms-1'
} +0ms
  feathers-distributed Initializing cote with options {
  helloInterval: 10000,
  checkInterval: 20000,
  nodeTimeout: 30000,
  masterTimeout: 60000,
  log: false,
  basePort: 10000,
  highestPort: 20000
} +2ms
  feathers-distributed Services subscriber ready for app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key ms-1 +2ms
  feathers-distributed Initializing feathers-distributed healthcheck route /distribution/healthcheck/ +0ms
info: Feathers app listening on http://localhost:3031
  feathers-distributed Services publisher ready for app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key ms-1 +1s
  feathers-distributed Service events publisher ready for local app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key ms-1 +1s
  feathers-distributed Service responder ready for local app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key ms-1 +1s
  feathers-distributed Registering listeners for  [ 'find', 'get', 'create', 'update', 'patch', 'remove', 'healthcheck' ] +1ms
  feathers-distributed:publish Scheduled local services publishing for app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key ms-1 +0ms
  feathers-distributed:register Registering remote app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key gateway +0ms
  feathers-distributed:register Service requester ready for remote app with uuid a2e46295-dad5-49f6-a3bd-c1373254a6d0 and key gateway for app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key ms-1 +1ms
  feathers-distributed:register Ignoring already registered remote app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key gateway +1ms
  feathers-distributed:register Ignoring already registered remote app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key gateway +0ms
  feathers-distributed:register Ignoring already registered remote app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key gateway +0ms
  feathers-distributed:register Ignoring already registered remote app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key gateway +1ms
  feathers-distributed:register Already registered local service on path users for app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key ms-1 +1ms
  feathers-distributed:register Already registered local service on path distribution/healthcheck/:key for app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key ms-1 +0ms
  feathers-distributed:register Already registered local service on path distribution/healthcheck for app with uuid 26b286b0-b5fc-4b2a-b0fe-580654a4bb45 and key ms-1 +0ms
/home/cdcr/code/feathers5-2/ms1/node_modules/@feathersjs/hooks/script/hooks.js:66
            throw new Error(`Can not apply hooks. '${method}' is not a function`);
                  ^

Error: Can not apply hooks. 'find' is not a function
    at objectHooks (/home/user/code/feathers5-2/ms1/node_modules/@feathersjs/hooks/script/hooks.js:66:19)
    at hooks (/home/user/code/feathers5-2/ms1/node_modules/@feathersjs/hooks/script/index.js:50:43)
    at Feathers.hookMixin (/home/user/code/feathers5-2/ms1/node_modules/@feathersjs/feathers/lib/hooks.js:137:23)
    at /home/user/code/feathers5-2/ms1/node_modules/@feathersjs/feathers/lib/application.js:116:40
    at Array.forEach (<anonymous>)
    at Feathers.use (/home/user/code/feathers5-2/ms1/node_modules/@feathersjs/feathers/lib/application.js:116:21)
    at Feathers.use (/home/user/code/feathers5-2/ms1/node_modules/@feathersjs/koa/lib/index.js:48:36)
    at Feathers.app.use (file:///home/user/code/feathers5-2/ms1/node_modules/@kalisio/feathers-distributed/lib/index.js:257:36)
    at registerService (file:///home/user/code/feathers5-2/ms1/node_modules/@kalisio/feathers-distributed/lib/register.js:88:7)
    at Subscriber.<anonymous> (file:///home/user/code/feathers5-2/ms1/node_modules/@kalisio/feathers-distributed/lib/index.js:35:5)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by nathanbrizzee-cdcr** [comment]
Update. I discovered that the error is caused by adding the middlewares section to the constructor.
```js
app.configure(
  feathersDistribution({
    hooks: {
      before: {
        all: [
        ]
      }
    },
    services: (service) => true,
    remoteServices: (service) => true,
    middlewares: {
      before: (req, res, next) => next(),
      // after: errorHandler()
    },
    key: "gateway",
  })
)
```

If I comment out the middlewares section, then both applications run fine.
```js
app.configure(
  feathersDistribution({
    hooks: {
      before: {
        all: [
        ]
      }
    },
    services: (service) => true,
    remoteServices: (service) => true,
    // middlewares: {
    //  before: (req, res, next) => next(),
    //  // after: errorHandler()
    // },
    key: "gateway",
  })
)
```

So it appears that koa doesn't support middlewares the way they are defined for express.  It also looks like I don't even need the middlewares section with koa. If I ask for a service that does not exist. I still get a 404.

```
{
    "name": "NotFound",
    "message": "Path /distribution/healthcheck2 not found",
    "code": 404,
    "className": "not-found"
}
```
