### ISSUE TITLE
When to initialized the library

### ISSUE THREAD

**Issue by dekelev** [kalisio/feathers-distributed#46]
It is unclear when the feathers-distributed library should be initialized. the docs suggest to do that after `app(hooks)`. does it means that it must be initialized after initializing all the services?

I've tried initializing at the end of the bootstrap and had no issues. Then I've tried initializing it before the services and before the authentication service initialization and got this error due to issue with the authentication service publishing:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "options.port" property must be one of type number or string. Received type object
    at lookupAndConnect (net.js:960:13)
    at Socket.connect (net.js:940:5)
    at SubSocket.Socket.connect (/opt/app/node_modules/@dashersw/axon/lib/sockets/sock.js:297:8)
    at Subscriber.onAdded (/opt/app/node_modules/cote/dist/components/subscriber.js:53:15)
    at Discovery.discovery.on.obj (/opt/app/node_modules/cote/dist/components/component.js:30:12)
    at Discovery.emit (events.js:187:15)
    at Discovery.EventEmitter.emit (domain.js:442:20)
    at Network.Discover.self.evaluateHello (/opt/app/node_modules/@dashersw/node-discover/lib/discover.js:176:9)
    at Network.emit (events.js:182:13)
    at Network.EventEmitter.emit (domain.js:442:20)
    at /opt/app/node_modules/@dashersw/node-discover/lib/network.js:72:22
    at Network.decode (/opt/app/node_modules/@dashersw/node-discover/lib/network.js:208:12)
    at Socket.<anonymous> (/opt/app/node_modules/@dashersw/node-distscover/lib/network.js:53:14)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at RedisClient.<anonymous> (/opt/app/node_modules/@dashersw/node-discover/lib/redis.js:22:14)
    at RedisClient.emit (events.js:182:13)
    at RedisClient.EventEmitter.emit (domain.js:442:20)
    at return_pub_sub (/opt/app/node_modules/redis/index.js:790:18)
    at RedisClient.return_reply (/opt/app/node_modules/redis/index.js:833:9)
    at JavascriptRedisParser.returnReply (/opt/app/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/opt/app/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/opt/app/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
```

After some debugging, it seems that the server was trying to connect to host with port `null`.

**Comment by claustres** [comment]
There are different things at play here about the initialization orders. I will try to be exhaustive and any help on this is much appreciated.

1) The library overrides [`app.use()`](https://github.com/kalisio/feathers-distributed/blob/master/src/index.js#L158) to automatically publish any new service defined, so that you can usually safely initialize it before registering your services like others feathers plugins (transport, configuration, etc.). However, you might also configure some middlewares with `options.middlewares` (https://github.com/kalisio/feathers-distributed/issues/26) and in this case you probably need to initialize the express plugin beforehand.

2) The library also tries to [immediately initialize](https://github.com/kalisio/feathers-distributed/blob/master/src/index.js#L153) the underlying cote module **unless you intentionally add some delay**. This delay can be required because it appears that in some scenarios (e.g. Docker deployment https://github.com/kalisio/feathers-distributed/issues/36) the network setup takes some time and cote is not able to correctly initialize (e.g. allocate ports) before. The error you have seems to be of this type, I guess cote did not find any open port on the host.

3) As the library also relies on cote components to publish/subscribe events, and this components take some time to initialize, [there is also a publication delay](https://github.com/kalisio/feathers-distributed/blob/master/src/index.js#L124) that is respected before publishing app services.

I am not completely happy with all of this and any way to improve is welcomed.

**Comment by dekelev** [comment]
Interesting, I'll give a thought.

I did debugged portfinder when I had this issue and noticed that it fails to bind on port the should be available and so on with the next ports, without success. that's probably because the network was somehow not ready yet as you mentioned.

**Comment by claustres** [comment]
I've just added a [tips](https://github.com/kalisio/feathers-distributed#tips) section in docs so I propose to close this issue, please reopen for anything that looks like a bug.
